services:
  - type: web
    name: lawrence-yao-portfolio
    env: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


